#ifndef EDITOR_EDITOR_DEFINE_H_
#define EDITOR_EDITOR_DEFINE_H_

#ifndef EDITOR_DEFAULT_MATERIAL_FILE_EXTENSION
#define EDITOR_DEFAULT_MATERIAL_FILE_EXTENSION ".material"
#endif

#ifndef EDITOR_DEFAULT_MODEL_FILE_EXTENSION
#define EDITOR_DEFAULT_MODEL_FILE_EXTENSION ".model"
#endif

#endif