#ifndef EDITOR_EDITOR_DEFINE_H_
#define EDITOR_EDITOR_DEFINE_H_

#ifndef EDITOR_PROJECT_FILE_EXTENSION
#define EDITOR_PROJECT_FILE_EXTENSION ".deproj"
#endif

#ifndef EDITOR_DEFAULT_MATERIAL_FILE_EXTENSION
#define EDITOR_DEFAULT_MATERIAL_FILE_EXTENSION ".material"
#endif

#ifndef EDITOR_DEFAULT_MODEL_FILE_EXTENSION
#define EDITOR_DEFAULT_MODEL_FILE_EXTENSION ".model"
#endif

#ifndef EDITOR_DEFAULT_SCENE_FILE_EXTENSION
#define EDITOR_DEFAULT_SCENE_FILE_EXTENSION ".scene"
#endif

#ifndef EDITOR_DOTNET_CLI_COMMAND_RESULT_SUCCESS
#define EDITOR_DOTNET_CLI_COMMAND_RESULT_SUCCESS 0
#endif

#endif